#!/bin/bash
# SVRN.app/Contents/MacOS/SVRN
#
# Entry point for the SVRN.app bundle.
#
# First run (no storage configured):
#   Writes a setup wizard script to /tmp/ and opens it in Terminal,
#   giving the user a visible, guided install experience.
#
# Subsequent runs:
#   Silently starts Python services and opens the dashboard in the browser.
#
# Path layout inside the bundle:
#   Contents/MacOS/SVRN           ← this script
#   Contents/Resources/python/    ← bundled Python 3.12
#   Contents/Resources/src/       ← SVRN source (config, dashboard, kiwix, menubar)
#   Contents/Resources/launcher/  ← launch.py

SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
MACOS_DIR="$(dirname "$SCRIPT_PATH")"
BUNDLE_CONTENTS="$(dirname "$MACOS_DIR")"
RESOURCES="$BUNDLE_CONTENTS/Resources"

PYTHON="$RESOURCES/python/bin/python3"
LAUNCHER="$RESOURCES/launcher/launch.py"

export HOME="${HOME:-/Users/$(id -un)}"
export PYTHONPATH="$RESOURCES/src"

# ── Verify bundled Python exists ──────────────────────────────────────────────

if [ ! -f "$PYTHON" ]; then
    osascript -e 'tell application "System Events" to display alert "SVRN Error" message "Bundled Python runtime not found. Please reinstall SVRN." as critical'
    exit 1
fi

# ── First-run detection ───────────────────────────────────────────────────────

CONFIG_FILE="$HOME/.config/svrn/config.json"
_is_first_run=true

if [ -f "$CONFIG_FILE" ] && grep -q '"storage_root"' "$CONFIG_FILE" 2>/dev/null; then
    _is_first_run=false
fi

# ── First run: open setup wizard in Terminal ──────────────────────────────────

if [ "$_is_first_run" = true ]; then
    SETUP_CMD="$(mktemp /tmp/svrn_setup_XXXXXX.command)"

    # Write the setup wizard with the bundle path embedded
    cat > "$SETUP_CMD" << SETUP_EOF
#!/bin/bash
# SVRN First-Run Setup Wizard
# Auto-generated by SVRN.app — safe to delete after setup completes.

SVRN_RESOURCES="$RESOURCES"
SVRN_PYTHON="$PYTHON"
SVRN_LAUNCHER="$LAUNCHER"

##FIRST_RUN_SETUP##

SETUP_EOF

    chmod +x "$SETUP_CMD"
    open -a Terminal "$SETUP_CMD"
    exit 0
fi

# ── Normal launch: start services silently ────────────────────────────────────

exec "$PYTHON" "$LAUNCHER" "$@"
